services:
  db:
    image: mysql:8.0
    container_name: mlp_db
    environment:
      MYSQL_DATABASE: 'mlp_db'
      MYSQL_ROOT_PASSWORD: 'mysql_pass'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - mlp_network

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: mlp_django_app
    volumes:
      - ./backend:/app/backend
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./admin/.env
    networks:
      - mlp_network

volumes:
  mysql_data:
  label_studio_data:

networks:
  mlp_network:
    driver: bridge
