# Generated by Django 5.2.1 on 2025-06-10 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.IntegerField()),
                ('total_predictions_number', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('model_version', models.CharField(max_length=255)),
                ('is_draft', models.BooleanField(default=True)),
                ('ml_type_name', models.CharField(max_length=255)),
                ('ls_project_id', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'), models.Index(fields=['updated_at'], name='projects_pr_updated_d6acc2_idx'), models.Index(fields=['title'], name='projects_pr_title_ba614c_idx'), models.Index(fields=['ml_type_name'], name='projects_pr_ml_type_022ec7_idx')],
            },
        ),
    ]
