# Generated by Django 5.2.1 on 2025-06-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_prediction_predictionresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="ml_type_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="model_version",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
