# Generated by Django 5.2.1 on 2025-08-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_alter_project_description_alter_project_ml_type_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="ml_type_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="model_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
