version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
      - /tmp/ai_ameasure_uploads:/tmp/ai_ameasure_uploads
      - ../../ai_ameasure/app/master:/app/app/master:ro
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload