# Generated by Django 5.2.5 on 2025-08-26 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='機能名')),
                ('feature_type', models.CharField(choices=[('ai_measurement', 'AI計測集計'), ('data_analysis', 'データ分析'), ('reporting', 'レポート機能'), ('user_management', 'ユーザー管理'), ('location_management', '拠点管理'), ('custom', 'カスタム機能')], max_length=50, verbose_name='機能タイプ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='利用可能')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '機能',
                'verbose_name_plural': '機能',
                'ordering': ['feature_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='拠点名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='利用可能ユーザー')),
            ],
            options={
                'verbose_name': '拠点',
                'verbose_name_plural': '拠点',
            },
        ),
        migrations.CreateModel(
            name='LocationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('settings', models.JSONField(blank=True, default=dict, null=True, verbose_name='拠点固有設定')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_features', to='locations.feature', verbose_name='機能')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_features', to='locations.location', verbose_name='拠点')),
            ],
            options={
                'verbose_name': '拠点機能設定',
                'verbose_name_plural': '拠点機能設定',
                'unique_together': {('location', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='features',
            field=models.ManyToManyField(through='locations.LocationFeature', to='locations.feature', verbose_name='利用機能'),
        ),
    ]
