# Generated by Django 5.2.5 on 2025-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-updated_at'], 'verbose_name': '拠点', 'verbose_name_plural': '拠点'},
        ),
        migrations.AddField(
            model_name='location',
            name='alert_level',
            field=models.CharField(choices=[('normal', '正常'), ('warning', '警告'), ('danger', '危険')], default='normal', max_length=20, verbose_name='アラートレベル'),
        ),
        migrations.AddField(
            model_name='location',
            name='folder_name',
            field=models.CharField(blank=True, help_text='バックエンドのフォルダ名', max_length=100, null=True, verbose_name='フォルダ名'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.CharField(blank=True, help_text='フロントエンド用の識別子', max_length=100, null=True, unique=True, verbose_name='拠点ID'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='経度'),
        ),
        migrations.AddField(
            model_name='location',
            name='measurement_count',
            field=models.IntegerField(default=0, verbose_name='計測ポイント数'),
        ),
        migrations.AddField(
            model_name='location',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='location',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='進捗率（%）'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地域'),
        ),
        migrations.AddField(
            model_name='location',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('active', 'アクティブ'), ('monitoring', 'モニタリング中'), ('completed', '完了'), ('planning', '計画中')], default='planning', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='location',
            name='total_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='トンネル全長（m）'),
        ),
        migrations.AddField(
            model_name='location',
            name='tunnel_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='トンネル名'),
        ),
    ]
