# Generated by Django 5.2.5 on 2025-08-26 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_options_location_alert_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['parent_feature__name', 'feature_type', 'name'], 'verbose_name': '機能', 'verbose_name_plural': '機能'},
        ),
        migrations.AddField(
            model_name='feature',
            name='parent_feature',
            field=models.ForeignKey(blank=True, help_text='この機能の親機能（指定した場合、親機能が有効になると自動で有効になります）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_features', to='locations.feature', verbose_name='親機能'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('ai_a_measurement', 'AI-A計測'), ('ai_measurement', 'AI計測集計'), ('prediction', '予測モデル作成'), ('simulation', '最終変位・沈下予測'), ('data_analysis', 'データ分析'), ('reporting', 'レポート機能'), ('user_management', 'ユーザー管理'), ('location_management', '拠点管理'), ('custom', 'カスタム機能')], max_length=50, verbose_name='機能タイプ'),
        ),
    ]
