# Generated by Django 5.2.5 on 2025-08-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_feature_options_feature_parent_feature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['display_order', 'id'], 'verbose_name': '機能', 'verbose_name_plural': '機能'},
        ),
        migrations.AddField(
            model_name='feature',
            name='display_order',
            field=models.IntegerField(default=0, help_text='表示順序（小さい値が先に表示）', verbose_name='表示順'),
        ),
    ]
