# Generated by Django 5.2.1 on 2025-06-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='group_projects', to='projects.project'),
        ),
    ]
